name: greenspace-accessibility-sabadell
channels:
  - conda-forge
  - bioconda
dependencies:
  - contextily=1.3.0
  - ipykernel
  - osmnx=1.3.1
  - papermill
  - pip
  - pip:
      - -e .
  - pystac=1.7.3
  - pystac-client=0.6.1
  - python=3.10
  - rioxarray=0.14.1
  - snakemake
  - stackstac=0.4.3
  - xarray=2023.5.0
